dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - openjdk8
  - oraclejdk8
install: true
script:  
  - java -version
  - mvn clean
  - mvn test
  - mvn install
branches:
  only:
    - master
    - develop